# Python for data analysis

#### Numpy Arrays

In [1]:
from numpy import array

In [2]:
# data1 is a list
data1 = [1.9, 2.1, 3.2, 4.1]

# Easily convert to numpy array
arr1 = array(data1)

In [3]:
arr1

array([1.9, 2.1, 3.2, 4.1])

This also includes multi-dimensional arrays

In [4]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = array(data2)

In [5]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

How many dimensions?

In [6]:
arr2.ndim

2

Show the size of the dimensions

In [7]:
arr2.shape

(2, 4)

Data types are inferred

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('int64')

Generating empty arrays

In [10]:
from numpy import zeros, empty

In [11]:
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
empty((2,3,2))

array([[[4.66430007e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [14]:
from numpy import arange

In [15]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Produce an identity matrix

In [16]:
from numpy import identity

In [18]:
identity(2)

array([[1., 0.],
       [0., 1.]])

#### Array arithmetic

In [19]:
arr1 * arr1

array([ 3.61,  4.41, 10.24, 16.81])

In [20]:
arr1 * 10

array([19., 21., 32., 41.])

In [21]:
1/arr1

array([0.52631579, 0.47619048, 0.3125    , 0.24390244])